services:
  web:
    image: 691950705664.dkr.ecr.us-east-1.amazonaws.com/docspring/enterprise
    resources:
      - database
      - redis
    # domain: docspring.example.com
    health:
      path: ${HEALTH_CHECK_PATH}
      grace: 20
      interval: 5
    command: run_as_deploy foreman start -m web=1
    labels:
      - convox.deployment.minimum=50
      - convox.draining.timeout=10
      - convox.health.threshold.healthy=2
      - convox.health.threshold.unhealthy=4
    scale:
      memory: 1400
      cpu: 700
      count: 3-10
      targets:
        cpu: 80
        memory: 90
        requests: 300
    environment:
      - "*"
      - WEB_CONCURRENCY=3
      - RAILS_MAX_THREADS=5
      - REQUEST_TIMEOUT=30
      - FORCE_SSL=true
      - PORT=4001
    port: 4001

  worker:
    image: 691950705664.dkr.ecr.us-east-1.amazonaws.com/docspring/enterprise
    resources:
      - database
      - redis
    command: run_as_deploy foreman start -m worker=1
    labels:
      - convox.deployment.minimum=50
    scale:
      memory: 1400
      cpu: 700
      count: 3-10
      targets:
        cpu: 80
        memory: 90
    environment:
      - "*"
      - FORCE_SSL=true

# -----------------------------------------------------------------
# WARNING: If you remove (or change the class) for any of these
# resources, Convox will delete them and you will lose your data.
# It is a good idea to sign into your AWS account and turn on
# "Termination Protection" for your RDS and ElastiCache resources.
# -----------------------------------------------------------------
resources:
  database:
    type: postgres
    options:
      class: db.t3.medium
      version: 9.6
      storage: 50
  redis:
    type: redis
    options:
      class: cache.t2.medium # (cache.t3.medium is not available yet)
      version: 6.0.5

timers:
  submissionExpiration:
    schedule: 0 9 * * ?
    command: bundle exec rake submissions:enqueue_expiry_jobs
    service: worker
